# stellar.toml
ACCOUNT="GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"
DOMAIN="antidumpalways.github.io"

[FEDERATION_SERVER]
FEDERATION_SERVER="https://antidumpalways.github.io/federation"

[TRANSFER_SERVER]
TRANSFER_SERVER="https://antidumpalways.github.io/transfer"

[TRANSFER_SERVER_SEP0024]
TRANSFER_SERVER_SEP0024="https://antidumpalways.github.io/transfer24"

[KYC_SERVER]
KYC_SERVER="https://antidumpalways.github.io/kyc"

[WEB_AUTH_ENDPOINT]
WEB_AUTH_ENDPOINT="https://antidumpalways.github.io/auth"

[HORIZON_URL]
HORIZON_URL="https://horizon-testnet.stellar.org"

[SIGNING_KEY]
SIGNING_KEY="GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"

[[CURRENCIES]]
code="TEST"
issuer="GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"
display_decimals=7
