# Stellar TOML Configuration File
# This file is served from /.well-known/stellar.toml

# Basic Configuration
ACCOUNTS = ["GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"]
VERSION = "1.0.0"
SIGNING_KEY = "GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

# Server Endpoints
WEB_AUTH_ENDPOINT = "https://testanchor.stellar.org/auth"
KYC_SERVER = "https://testanchor.stellar.org/sep12"
TRANSFER_SERVER = "https://testanchor.stellar.org/sep6"
TRANSFER_SERVER_SEP0024 = "https://testanchor.stellar.org/sep24"
DIRECT_PAYMENT_SERVER = "https://testanchor.stellar.org/sep31"
ANCHOR_QUOTE_SERVER = "https://testanchor.stellar.org/sep38"

# Horizon endpoint
HORIZON_URL = "https://horizon-testnet.stellar.org"

# Documentation
[DOCUMENTATION]
ORG_NAME = "Stellar Home Domain Quest"
ORG_URL = "https://stellar-home-domain.vercel.app/"
ORG_DESCRIPTION = "A Stellar blockchain integration project for home domain configuration and testing."
ORG_GITHUB = "stellar-home-domain-quest"

# Currencies
[[CURRENCIES]]
code = "TEST"
issuer = "GBTDYXVX54UNZUY3GWGQKVRAXXCNGUFINLT5G6BHUZBDYW6FSIOZZWVM"
status = "test"
is_asset_anchored = false
anchor_asset_type = "crypto"
desc = "TEST Token for Stellar Home Domain Quest project testing purposes."

[[CURRENCIES]]
code = "USDC"
issuer = "GA5ZSEJYB37JRC5AVCIA5MSE4EP3MCSIPN6CH7JSQVRACXDBQY62VUQ2"
status = "test"
is_asset_anchor = true
anchor_asset_type = "fiat"
desc = "USD Coin - Digital representation of US Dollar"

[[CURRENCIES]]
code = "native"
status = "test"
is_asset_anchored = false
anchor_asset_type = "crypto"
desc = "XLM, the native asset of the Stellar network."
